puts "Coding is fun!!!!!!"
puts "david is obsessed"
puts "noooo"
puts "josh ur stupid. you get b in ap lang"
puts "david is a tryhard"
puts "making a change is difficult"
puts "I don't get this"
puts "Make another change"
puts "Make a change at home"
puts "Change at home completed"